spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://192.168.1.140:3306/test_l?autoReconnect=true&useSSL=false
        username: root
        password: root
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.hbm2ddl.auto: update
    redis:
        host: 192.168.1.140
        port: 6379
        password:
        timeout: 3000
        pool:
            maxActive: 500
            maxIdle: 300
            maxWait: 2000
    kafka:
        producer:
            batch-size: 16384
            retries: 0
            buffer-memory: 33554432
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
        bootstrap-servers: 192.168.1.3:9092
        consumer:
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            group-id: springboot-group2
            auto-offset-reset: earliest
            auto-commit-interval: 100
            enable-auto-commit: true
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    #data:
        #solr:
            #host: http://118.25.104.54:8983/solr/techproducts


server:
    port: 1219